let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`“${pickRandom(global.bucin)}”`, m)
}
handler.help = ['desamor']
handler.tags = ['quotes']
handler.command = /^(desamor)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

// https://jalantikus.com/tips/kata-kata-bucin/
global.bucin = [
 "Elijo estar solo, no porque espere la perfecta, sino porque necesito una que nunca se rinda.",
 "Se crea un solo con un socio que aun no ha encontrado.",
 "Soltero. Tal vez esa es la manera de Dios de decir 'Descansa del amor equivocado'.",
 "Los solteros son jovenes que anteponen su desarrollo personal a un amor mas elegante en el futuro.",
 "No estoy buscando a alguien perfecto, pero estoy buscando a alguien que se convierta en perfecto gracias a mis fortalezas.",
 "Los novios de la gente son nuestros almas gemelas retrasadas.",
 "Los solteros deben haber pasado. Todo hay un tiempo, en el que toda soledad se convierte en una union con el amante halal. Tenga paciencia.",
 "Romeo voluntariamente murio por Julieta, Jack murio salvando a Rose. El punto es, si quieres vivir, ser soltero.",
 "Estoy buscando a un hombre que no por sus excesos, pero estoy buscando a un hombre de sinceridad de su corazon.",
  "Las almas gemelas no son chanclas, que a menudo se intercambian. Asi que mantente en la lucha apropiada.",
 "Si eres una cuerda de guitarra, no quiero ser el guitarrista. Porque no quiero tu calidad.",
 "Si amarte es una ilusion, entonces dejame imaginarme para siempre.",
 "Miel... Mi trabajo es solo amarte, no contra el destino.",
 "Cuando estoy contigo es como una hora y un segundo, pero si estoy lejos de ti es como 1 dia a 1 año.",
 "Banana compote sabe sumedang, a pesar de que la distancia se extiende mi amor nunca desaparecera.",
 "Quiero ser el unico, no uno de ellos.",
 "No puedo prometer ser una buena. Pero prometo que siempre estare contigo.",
 "Si yo fuera un representante de la gente habria fallado, ¿como habria fallado la gente mikirin si todo lo que siempre tuve en mente fueras tu.",
 "Mira mi jardin, lleno de flores. Mira tus ojos, mi corazon esta floreciendo.",
 "Prometeme quedarme conmigo ahora, mañana y para siempre.",
 "Cariño... Mi trabajo es solo amarte, no contra el destino.",
 "Cuando estoy contigo es como una hora y un segundo, pero si estoy lejos de ti es como 1 dia a 1 año.",
 "Banana compote sabe sumedang, a pesar de que la distancia se extiende mi amor nunca desaparecera.",
 "Quiero ser el unico, no uno de ellos.",
 "No puedo prometer ser una buena. Pero prometo que siempre estare contigo.",
 "Si yo fuera un representante de la gente habria fallado, ¿como habria fallado la gente mikirin si todo lo que siempre tuve en mente fueras tu.",
 "Mira mi jardin, lleno de flores. Mira tus ojos, mi corazon esta floreciendo.",
 "Prometeme quedarme conmigo ahora, mañana y para siempre.",
 "El anhelo no solo surge debido a la distancia separada. Pero tambien por un deseo que no se materializa.",
 "Nunca estaras lejos de mi, dondequiera que vaya siempre estas ahi, porque siempre estas en mi corazon, que esta lejos solo nuestros cuerpos no son nuestros corazones.",
 "Se que en cada mirada que tengo, estamos obstaculizados por la distancia y el tiempo. Pero estoy seguro de que seremos capaces de unirnos.",
 "Extrañarte sin verte es como crear una cancion que nunca se divierte.",
 "Hay momentos en que la distancia siempre es una barrera entre tu y yo, pero todavia en mi corazon siempre estamos cerca.",
 "Si este corazon no es capaz de detener todo anhelo, ¿que poder puedo hacer sino orar por ti.",
 "Tal vez en este momento solo puedo resistirme a este anhelo. Hasta entonces puedo conocer y soltar este anhelo contigo.",
 "A traves de un anhelo tumultuoso en mi corazon, alli a veces necesito desesperadamente un abrazo de su afecto.",
 "En el frio de la noche, ya no recuerdo; ¿Con que frecuencia creo que te extrañas tambien.",
 "Extrañarte es como una lluvia que viene de repente y dura mucho tiempo. E incluso despues de que la lluvia disminuyo, mi anhelo todavia se sentia.",
 "Desde que te conozco innatamente quiero aprender mas, aprender a ser lo mejor para ti.",
 "¿Sabes la diferencia entre tu cara y tu cara? Si el lapiz puede ser borrado, pero si tu cara no sera algo que pueda ser borrado de mi mente.",
 "Una cosa acerca de la felicidad en la escuela que me mantiene emocionado es poder ver tu sonrisa todos los dias.",
 "¿Sabes que no es ninguna diferencia si vas a la misma escuela a tu casa? Kalo a la escuela debe ser llevado libros y boligrafos, pero si vas a tu casa, solo traigo corazon y amor.",
 "No estoy triste si mañana es lunes, estoy triste si no te veo.",
 "Mi momento de amor es perpendicular a tu momento de amor. Haz de nuestro amor el punto de equilibrio perfecto.",
 "Estoy dispuesto a participar en una carrera alrededor del mundo, siempre y cuando el engkai sea la linea de meta.",
 "Mi tarea es extrañarte. Mas fuerte que las matematicas, mas amplio que la fisica, mas dificil que la biologia.",
 "Mi amor por ti es como el metabolismo, que no dejara de morir.",
 "Si la cebada es rica tu, ven a recoger, vete a casa, anter deh.",
 "Come lo que quiera mientras estes, incluyendo comer ati.",
 "El amor es rico en la pena de muerte. Si no te disparan, estas ahorcado.",
 "Amarte es como las drogas: una vez trata de ser un opiaceo, no trata de hacer curioso, dejado para hacer sakaw.",
 "Me gusta mas picar porque comer es bueno. Ademas, ¿tienes completamente...",
 "Este mundo nos pertenece a los dos. Los otros solo se estan contratando.",
 "Para mi, todos esos dias son martes. Martes en el cielo cuando estas cerca ...",
 "¿Y si los dos nos convertimos en una conspiracion de criminales? Te robe el corazon y tu me robaste el mio",
 "Eres como el cafe que tome esta mañana. Amargo, pero obten ganancias",
 "A menudo tengo celos de tu lapiz labial. Ella puede sonreirte todos los dias, desde la mañana hasta la noche",
 "Solo escuchar tu nombre puede hacerme sonreir como un tonto.",
 "Se que tu novia no es la unica y que agradarle no es solo a mi.",
 "Desde que deje de esperarte, me desanime en todo ...",
 "Contigo, enamorarse es el desamor mas deliberado",
 "Es muy dificil sentir la felicidad de la vida sin tu presencia a mi lado.",
 "A traves del anhelo que es turbulento en mi corazon, a veces realmente necesito abrazar tu amor.",
 "Si supieras, hasta el dia de hoy todavia te amo",
 "A veces envidio la cometa ... la cuerda esta rota, todavia esta siendo perseguida y no esta dispuesta a ser capturada por otros ...",
 "No sabia lo que era el amor, hasta que finalmente te conoci. Pero, en ese momento supe que era desgarrador.",
 "Perseguir es agotador, pero aun mas agotador es esperar \nEsperar a que te des cuenta de que existo ...",
 "No dejes de amar solo porque te han herido. Porque no hay arcoiris sin lluvia, no hay amor verdadero sin llorar.",
 "Tengo un millon de razones para olvidarte, pero nada puede obligarme a dejar de amarte.",
 "A veces alguien se siente tan estupido por amar a alguien",
 "Eres la mejor angustia de la que me he arrepentido",
 "No vale la pena esperar, es solo que a menudo da falsas esperanzas",
 "Una parte de mi se siente enferma. Recordar que esta tan cerca, pero intacto.",
 "Lo mejor de amar a alguien es orar en secreto por ellos.",
 "Espero poder deshacerme de este sentimiento tan pronto como te pierda",
 "Por amor nos engañamos a nosotros mismos. Esforzarse mucho en realidad cae irrespetuosamente",
 "Piensa en mi como en tu casa, si vas entiendes a donde ir a casa. Quedate si quieres y vete si estas aburrido ...",
 "Estoy confundido, ¿deberia estar decepcionado o no? Si estoy decepcionado, ¿quien soy yo para el?\n\nSi no estoy decepcionado, pero estoy esperando que el diga.",
 "Mi anhelo es como una ramita que se queda en pie. Aunque ninguna de las hojas la acompañe, hasta que finalmente se seca, se rompe y muere.",
 "Creo que ahora somos solo dos extraños que tienen los mismos recuerdos.",
 "Haz que te odie aunque sea por unos minutos, para que no sea muy dificil olvidarte.",
 "Te amo con todo mi corazon, pero en cambio compartes tus sentimientos con los demas",
 "Amarte puede destruirme, pero de alguna manera dejarte no me arregla.",
 "Tu eres el principal y el primero en mi vida. Pero yo soy el segundo para ti",
 "Si tan solo pudieramos encontrarnos en un sueño, dormiria para siempre.",
 "Verte feliz es mi felicidad, incluso si eres feliz sin mi.",
 "A veces tengo celos de un objeto. No tiene sabor pero siempre se necesita. A diferencia de mi que tiene gusto, pero es abandonado e ignorado ...",
 "¿Como puedo moverme si solo a ti mi corazon se detiene?",
 "Los recuerdos de ti son como un hogar para mi. De modo que cada vez que mi mente divague, seguramente los extremos siempre volveran a ti",
 "¿Por que es util el tejido? Porque el amor nunca se seca. - Sujiwo Tejo",
 "Si amarte es un error, dejame seguir equivocado",
 "Desde que te conoci, quiero seguir aprendiendo. Aprender es lo mejor para ti",
 "Alguien actuo como estupido solo para verte sonreir. Y estaba feliz por eso",
 "No soy una buena persona, pero aprendere a ser el mejor para ti",
 "No estamos muertos, pero son las heridas las que nos impiden caminar como soliamos hacerlo",
 "Tu presencia es como una taza de cafe que necesito todas las mañanas, lo que puede mantenerme motivado para pasar el dia",
 "Tengo muchas ganas de darte el mundo. Pero como no es posible, dare lo mas importante de mi vida, que es mi mundo",
 "La reparacion es graciosa pero dulce, mas que a veces romantica pero en ultima instancia tragica",
 "Ben finalmente no esta decepcionado. Necesitamos saber cuando tener esperanza y cuando detenernos",
 "No necesitas ser hermosa y rica, estoy bastante seguro de que eres feliz",
 "Mi amor por ti es como una camara, el enfoque en ti es como si me estuviera borrando",
 "Todos los dias sueño, pero no puedo tenerlo",
 "No verte durante 30 dias parece un mes",
 "Estoy sin ti como un gato sego perdio la goma. Ambyar.",
 "Me gustaria poder jugar. Para poder encontrarte mas rapido. Ben Mas tiempo tengo para vivir contigo.",
 "Nunca supe lo que era amar, excepto una vez que te conoci",
 "El amor de 𝓛 por visitar a 𝐒 no se perdera incluso si 𝐒 se casa de nuevo",
 "Mi paciencia es limitada, pero mi amor por ti es infinito",
 "mi cariño hacia ti no se desvanecera incluso si muero.",
 "Recuerdos asombrosos de estar junto a ti para luego recordados hasta que los olvidas.",
 "No podre vivir solo, necesito la ayuda de otras personas",
 "Mi paciencia es limitada, pero mi amor por ti nunca terminara",
 "Quiero sentir que recopilo todas las palabras de amor que hay en este mundo, y luego pasa por mi lado a recopilar, para que conozcas mi inmenso sentido del amor por ti",
 "Calmate, mi amor por ti es ilimitado el tiempo no se acabara.",
 "No soy la persona perfecta para ti, ni la mejor para ti. Pero seguro, soy la unica persona que sigue esforzandose por hacerte feliz",
 "Es suficiente que la red se pierda, tu no",
 "Mis enemigos son los que tambien quieren intentar conseguirte.",
 "Muchos siempre estan ahi, pero si eres el unico que quiero, ¿que te parece?",
 "Mis horas de sueño se ven arruinadas por la nostalgia.",
 "Basta con que China este lejos, no deberiamos amarla.",
 "Lo importante es tu felicidad, yo no soy importante ..",
 "Solo un deseo, ser amado por ti ..",
 "Estoy sin ti como una ambulancia sin wiuw wiuw",
 "Es suficiente que la Antartida este lejos. No la Antartida.",
]
